# Generated by Django 4.2.20 on 2025-04-08 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazin_online', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantitate', models.PositiveIntegerField(default=1)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazin_online.comanda')),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazin_online.produs')),
            ],
            options={
                'verbose_name_plural': 'Iteme_Comanda',
            },
        ),
        migrations.AddField(
            model_name='comanda',
            name='produse',
            field=models.ManyToManyField(through='magazin_online.ItemComanda', to='magazin_online.produs'),
        ),
    ]
