# Generated by Django 4.2.20 on 2025-04-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin_online', '0003_comanda_status_comanda'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='platita',
            field=models.CharField(default='Nu', max_length=10),
        ),
    ]
