# Generated by Django 4.2.20 on 2025-04-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin_online', '0004_comanda_platita'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='adresa_livrare',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comanda',
            name='metoda_livrare',
            field=models.CharField(choices=[('curier', 'Curier'), ('posta', 'Posta')], default='curier', max_length=20),
        ),
        migrations.AddField(
            model_name='comanda',
            name='metoda_plata',
            field=models.CharField(choices=[('cash', 'Cash la livrare'), ('card', 'Card')], default='card', max_length=20),
        ),
        migrations.AddField(
            model_name='comanda',
            name='nume_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comanda',
            name='telefon_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='platita',
            field=models.CharField(choices=[('Efectuata', 'Platita'), ('Neefectuata', 'Neplatita')], default='Neefectuata', max_length=20),
        ),
    ]
