# Generated by Django 4.2.20 on 2025-04-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin_online', '0006_alter_comanda_status_comanda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='status_comanda',
            field=models.CharField(choices=[('deschisa', 'Deschisa'), ('plasata', 'Plasata'), ('in procesare', 'In procesare'), ('expediata', 'Expediata'), ('livrata', 'Livrata'), ('anulata', 'Anulata')], default='deschisa', max_length=20),
        ),
    ]
